version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
       - 6379:6379
  mysql:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
    ports:
       - 3306:3306
  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
        - 5432:5432
  mongo:
        image: mongo
        ports:
                - 27017:27017
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - data:/data
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  data:
